name: open_earable_flutter
description: This package provides functionality for interacting with OpenEarable devices. Control LED colors, control audio, and access raw sensor data.
version: 2.3.7
repository: https://github.com/OpenEarable/open_earable_flutter/tree/main

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  typed_data: ^1.4.0
  convert: ^3.1.2
  permission_handler: ^12.0.1
  universal_ble: ^1.2.0
  logger: ^2.7.0
  # for fota:
  equatable: ^2.0.8
  file_picker: ^11.0.2
  flutter_archive: ^6.0.4
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  json_annotation: ^4.9.0
  mcumgr_flutter: ^0.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  tuple: ^2.0.2
  uuid: ^4.5.3
  bloc: ^9.2.1
  meta: ^1.18.2
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/wearable_icons/open_earable_v1/
    - assets/wearable_icons/open_earable_v2/
    - assets/wearable_icons/open_ring/
    - assets/wearable_icons/cosinuss_one/
    - assets/wearable_icons/polar/default/
    - assets/wearable_icons/polar/watch/
    - assets/wearable_icons/polar/strap_sensor/
